version: 2

project_name: prview

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/prview
    binary: prview
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: flatcoke
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/flatcoke/prview"
    description: "GitHub-style git diff viewer in your browser"
    license: "MIT"
    install: |
      bin.install "prview"
    test: |
      system "#{bin}/prview", "--help"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
